### ISSUE TITLE
Get EditProfileActivity to actually edit the user profile

### ISSUE THREAD

**Issue by scveloso** [ubclaunchpad/Room8#40]
**AT:**
-Firebase user object is updated when “Edit Profile” is clicked with different fields
-Fields are properly populated when EditProfileActivity is opened

**Description:**
Right now, user data shows up in the fields(good).
![Screen Shot 2018-11-24 at 10.37.50 AM.png](https://images.zenhubusercontent.com/5a511f2fa016c5b034bc42f5/2672043c-f1f8-43a8-87b5-732b92cb2e5c)
But now, when the user presses “Edit Profile”, these changes should reflect on the user object in Firebase.

**Comment by hyunuk71** [comment]
I successfully implemented editing the first and last name.
However, I didn't find how to check the validity between the current password and the password of user input.
Instead of that, changing a password in Firebase requires and checks that a user has recently signed in. 
So I'll just implement update password method and requires that user should input the new password twice.
